window:
  decorations: none
  startup_mode: Maximized
font:
  normal:
    family: PlemolJP35 Console NF
    style: Regular
  bold:
    style: SemiBold
  italic:
    style: Italic
  bold_italic:
    style: SemiBold Italic
  size: 15.0
selection:
  save_to_clipboard: true
