[font]
size = 15.0

[font.bold]
style = "SemiBold"

[font.bold_italic]
style = "SemiBold Italic"

[font.italic]
style = "Italic"

[font.normal]
family = "PlemolJP35 Console NF"
style = "Regular"

[window]
decorations = "None"
startup_mode = "Maximized"

[mouse]
hide_when_typing = true

[selection]
save_to_clipboard = true
